### ISSUE TITLE
help with using this ¿

### ISSUE THREAD

**Issue by sandwichwater** [dbry/adpcm-xq#12]
hello , sorry if im overlooking something really obvious or using this incorrectly , but i cant seem to be able to be able to use this , my first guess was a simple drag and drop onto the .exe after it didnt run when opened  but that doesnt seem to be do anything either , and there arent any other files shipped along with the .exe , so ive come to the conclusion that im missing something . sorry again if im overlooking something obvious but i tested a bunch and read the github page and just really cant figure out how to use this . any help would be super appreciated

**Comment by dbry** [comment]
Hi! Unfortunately, the converter is a command-line program, not an installer, so yeah, you might see a brief flash on the screen when you double-click it, but that's about it.

There are tons of web pages about using the "Command Prompt" to run programs like this, but here's a start guide (don't type what I put in parens):

1. Create a folder on your desktop with the `adpcm-xq.exe` program **and** the .wav file(s) you want to convert. Use a simple name like **`adpcm`**
2. Start the Command Prompt (Start menu?)
3. type **`cd Desktop`** (this takes you into the desktop)
4. type **`cd adpcm`** (this goes into the directory you made)
5. type **`dir`** (this _should_ display the names of everything in the directory, which should look familiar)
6. type **`adpcm-xq file1.wav file1-adpcm.wav`** (this should convert the first file if it was called **`file1.wav`**, otherwise use the actual names you want)
7. type **`dir`** again to see the file you just made, or look in the folder on the desktop
8. double-click on the adpcm file to make sure everything went well

Hope this helps and good luck!

**Comment by sandwichwater** [comment]
this did work , thankyou ! command prompt is usually where my knowledge of computers and programs falls short so a step by step process was extremely helpful , thankyou again
