### ISSUE TITLE
Min blocksize is 256?

### ISSUE THREAD

**Issue by davidgfnet** [dbry/adpcm-xq#2]
Hello!
Cool work, many thanks for sharing it! Quality is really good, I cannot distinguish it really.
Why is not possible to set -b to a number smaller than 8? I tried it and I do see weird things going on. Could you mention the main points that would need to be reworked to support, say 128 or 64 byte blocks? I'd like to give it a try with 32 bytes :D
Also does the standard support something bigger than 4 bits per sample? I'd like to compress 16bit/stereo/44.1kHz audio just a bit, say half the bandwidth for instance. Is ADPCM still useful?
Thanks!

**Comment by dbry** [comment]
Other than the check in adpcm-xq.c, I don't see any reason that smaller block sizes should not work. I just tried down to 16 bytes per block and it seemed to work fine (with changing the check, obviously).

There are a few issues though. First, there's 7 bytes of overhead per [stereo] block, so if you only have 32 byte blocks, the overhead starts to become pretty significant. Also, the code here cannot use the next block in part of the quality optimization calculations, and so the more often you generate a new block the worse the quality will be.

There are definitely 3-bit and 5-bit versions of IMA ADPCM, but I'm not sure how “standard” they are, meaning a lot of players don't support them. My whole idea here was to generate something standard, so I didn't bother with them (plus packing 3 or 5 bits in bytes is a lot more cumbersome).

And yeah, something like an 8-bit ADPCM would be really high quality. Actually, with 8 bits per sample you can implement something completely transparent very easily (even easier than ADPCM). You can also try something like WavPack lossy, which can be used at 8 bits per sample, and is much better than ADPCM at lower bitrates too. Of course, it uses more CPU (not sure if that's why you're looking at ADPCM).

Cheers!

-David

**Comment by Davedson-debug** [comment]
> Also, the code here cannot use the next block in part of the quality optimization calculations, and so the more often you generate a new block the worse the quality will be.

So you basically mean that decreasing the block size in your encoder will actually WORSEN the quality? and if that's the case, that also means that using -b15 should give the best results quality-wise

**Comment by dbry** [comment]
> > Also, the code here cannot use the next block in part of the quality optimization calculations, and so the more often you generate a new block the worse the quality will be.
> 
> So you basically mean that decreasing the block size in your encoder will actually WORSEN the quality? and if that's the case, that also means that using -b15 should give the best results quality-wise

Actually I misspoke when I said that the quality is worse with smaller blocks. There _is_ a small penalty at the end of each block because of the lack of look-ahead there, but this is more than compensated for by the extra data sent at the beginning of the next block (the first sample of each block has no error because it is sent literally). And I just did a quick test to verify that shorter blocks do indeed encode _slightly_ better. But I don't think it makes sense to use shorter blocks to improve quality because the increased overhead means the files are larger.

Similarly, longer blocks are going to result in smaller files because of the reduced overhead, but they're also not standard. When I was just experimenting with longer blocks I found that Cool Edit 2000 would not read files with blocks longer than 4096 samples. Of course, at that point any size improvement with using longer blocks would be way under 1%.

**Comment by Davedson-debug** [comment]
oh well, in that case you might as well set -b8 as the default value, since it produces better quality output with little to no size difference from the default -b11 or even the -b15 (several hundreds kilobytes at worst)

**Comment by dbry** [comment]
Actually the difference between -b8 and -b11 is almost 2.5% and the difference in noise is so tiny that I couldn't have measured it except Cool Edit displays level in hundredths of a dB. I don't think that trade-off makes sense.

Also, the program doesn't just default to -b11; it's actually based on the sample rate and I don't think I just pulled that out of thin air...there must be a recommendation somewhere that I followed (although I can't find it now).

Anyway, this is why there's an option to set it!
